In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


### Exercise

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

In [46]:
import numpy as np
#imports the NumPy library. We use np inorder for us to type np instead of numpy every time we call a function.

nested_list = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(nested_list)

#I define a list containing two three lists. It has 3 rows and 3 columns.

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Using a property of the ndarray object
      - e.g. `A.shape`

In [13]:
nested_list.shape
#in this code it indicates the dimensions of the array.

(3, 3)

2. Using a method of the ndarray object
      - e.g. `A.max()`

In [14]:
nested_list.max()

#us to look for the largest value in the array.

np.int64(90)

3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

In [17]:
np.max(nested_list)

#it is a general NumPy tool and pass the array A into it as an input.

np.int64(90)

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

In [36]:
ones_array = np.ones((5, 5), dtype=int)

#This tells NumPy to create a matrix with 5 rows and 5 columns, filling every cell with the number 1.
# The int indicates that the number is an integer.

In [47]:
ones_array.size

# This code calculates the total count of numbers in the array.

25

In [41]:
ones_array.shape

#This code will show the structure of the array is a 5x5 grid.

(5, 5)

In [48]:
ones_array.ndim

#this will show that it is a 2D array. It will consist the x and y.

2

C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

In [52]:
value_array = np.arange(-5, 6)
print(value_array)
#np.arange will indicate that the number will start at -5 and stops before 6, creating an array of integers: [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5].

[-5 -4 -3 -2 -1  0  1  2  3  4  5]


In [50]:
result = value_array * 2

#using the code, NumPy automatically applies the * 2 to every element in the array simultaneously.

In [53]:
print(result)

#this will show the output

[-10  -8  -6  -4  -2   0   2   4   6   8  10]
